# Server Port
server.port=4000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/users-db
spring.data.mongodb.auto-index-creation=false

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
